INPUT:
  SIZE: (32, 32)
  CROP_PADDING: 4  # size * 0.125
  # Normalizes to [-1, 1] range
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  # Weak augmentations
  # FIXME The paper uses flip-and-shift (remove flip for digit datasets?)
  TRANSFORMS: ["random_crop", "normalize"]
  # TRANSFORMS: ["random_flip", "random_crop", "normalize"]

DATASET:
  # Domains: {'mnist', 'mnist_m', 'svhn', 'syn', 'usps'}
  NAME: "Digit5"

MODEL:
  BACKBONE:
    NAME: "wide_resnet_28_2"
    PRETRAINED: False
